# Generated by Django 5.2.10 on 2026-02-13 02:38

from django.db import migrations, models


def migrate_group_classes(apps, schema_editor):
    """Copy each group's class_enrolled into the new classes M2M."""
    Group = apps.get_model('attendance', 'Group')
    for g in Group.objects.all():
        if g.class_enrolled_id:
            g.classes.add(g.class_enrolled_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_student_groups_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='groups', to='attendance.class'),
        ),
        migrations.RunPython(migrate_group_classes, noop),
        migrations.RemoveField(
            model_name='group',
            name='class_enrolled',
        ),
    ]
