# Generated by Django 5.2.10 on 2026-02-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_group_many_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='attendance.class', verbose_name='Subjects'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='attendance.group', verbose_name='Groups'),
        ),
    ]
