# Generated by Django 5.2.10 on 2026-02-13 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_student_user_link'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date', 'class_enrolled')},
        ),
    ]
